import express from 'express';
import path from 'path';
import cors from 'cors';
import { createServer as createViteServer } from 'vite';
import { GoogleGenAI } from '@google/genai';
import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config();

const app = express();
const PORT = 3000;

// Supabase Admin client for server-side operations
const supabaseAdmin = createClient(
  process.env.VITE_SUPABASE_URL || '',
  process.env.SUPABASE_SERVICE_ROLE_KEY || ''
);

// Gemini Client
const ai = new GoogleGenAI({ 
  apiKey: process.env.GEMINI_API_KEY as string 
});

app.use(cors());
app.use(express.json({ limit: '10mb' }));

// API: Seed Wardrobe
app.post('/api/seed', async (req, res) => {
  try {
    const { garments } = req.body;
    if (!garments || !Array.isArray(garments)) {
      return res.status(400).json({ error: 'Invalid garments data' });
    }

    const { data, error } = await supabaseAdmin
      .from('garments')
      .insert(garments)
      .select();

    if (error) throw error;

    res.json({ success: true, count: data.length });
  } catch (error: any) {
    console.error('Seed error:', error);
    res.status(500).json({ error: error.message || 'Failed to seed wardrobe' });
  }
});

// API: Try On
app.post('/api/tryon', async (req, res) => {
  try {
    const { userId, userPhotoUrl, garmentId } = req.body;

    if (!userId || !userPhotoUrl || !garmentId) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    // 1. Check user credits
    const { data: profile, error: profileError } = await supabaseAdmin
      .from('profiles')
      .select('credits')
      .eq('id', userId)
      .single();

    if (profileError || !profile) {
      return res.status(404).json({ error: 'Profile not found' });
    }

    if (profile.credits < 1) {
      return res.status(402).json({ error: 'Insufficient credits' });
    }

    // 2. Get garment details
    const { data: garment, error: garmentError } = await supabaseAdmin
      .from('garments')
      .select('*')
      .eq('id', garmentId)
      .single();

    if (garmentError || !garment) {
      return res.status(404).json({ error: 'Garment not found' });
    }

    // 3. Prepare images for Gemini
    const fetchImageBase64 = async (url: string) => {
      const response = await fetch(url);
      const buffer = await response.arrayBuffer();
      return Buffer.from(buffer).toString('base64');
    };

    const userPhotoBase64 = await fetchImageBase64(userPhotoUrl);
    const garmentPhotoBase64 = await fetchImageBase64(garment.reference_image_url);

    const tryOnPrompt = `
You are performing a virtual clothing try-on. You are given two images:
Image 1 = the person (preserve exactly)
Image 2 = the garment reference (preserve exactly)

Rules, in strict priority order:
1. Preserve the person's face, skin tone, hairstyle, and body proportions from Image 1 with zero alteration. Do not beautify, resize, or change identity.
2. Replace only the clothing area with the garment shown in Image 2. Match its exact fabric pattern, color, embroidery, and silhouette — do not invent a generic version of the garment.
3. Preserve the original pose, camera angle, and background from Image 1.
4. Adjust the garment's drape and folds naturally to fit the person's body and pose — it should look physically worn, not pasted on.
5. Match lighting and shadow direction on the garment to the lighting already present on the person in Image 1.
6. Output a single photorealistic image, no text, no watermark, no side-by-side comparison.

Garment details for reference: ${garment.name}, ${garment.description || ''}, ${garment.fabric_type || ''}, ${garment.color_details || ''}.
    `;

    // 4. Call Gemini
    // Using gemini-1.5-flash as the reliable model for this task
    const result = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: [
        {
          role: 'user',
          parts: [
            { text: tryOnPrompt },
            { inlineData: { mimeType: 'image/jpeg', data: userPhotoBase64 } },
            { inlineData: { mimeType: 'image/jpeg', data: garmentPhotoBase64 } }
          ]
        }
      ]
    });

    const response = result; // In this SDK, result is the response
    let resultBase64 = '';
    
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        resultBase64 = part.inlineData.data;
        break;
      }
    }

    // Fallback if no inlineData returned (some models might return text or fail to generate image in this specific way if not tuned)
    if (!resultBase64) {
      throw new Error('No image generated by Gemini. Ensure the prompt and model support image output.');
    }

    // 5. Upload result to Supabase Storage
    const fileName = `result_${userId}_${Date.now()}.png`;
    const { data: uploadData, error: uploadError } = await supabaseAdmin.storage
      .from('tryon-results')
      .upload(fileName, Buffer.from(resultBase64, 'base64'), {
        contentType: 'image/png'
      });

    if (uploadError) {
      throw uploadError;
    }

    const { data: { publicUrl: resultImageUrl } } = supabaseAdmin.storage
      .from('tryon-results')
      .getPublicUrl(fileName);

    // 6. Deduct credit and record history
    await supabaseAdmin.from('profiles').update({ credits: profile.credits - 1 }).eq('id', userId);
    
    const { data: historyEntry, error: historyError } = await supabaseAdmin.from('tryon_history').insert({
      user_id: userId,
      garment_id: garmentId,
      user_photo_url: userPhotoUrl,
      result_image_url: resultImageUrl,
      status: 'completed'
    }).select().single();

    if (historyError) {
      console.error('Error saving history:', historyError);
    }

    // 7. Record transaction
    await supabaseAdmin.from('credit_transactions').insert({
      user_id: userId,
      amount: -1,
      type: 'tryon_spend'
    });

    res.json({ resultImageUrl, historyId: historyEntry?.id });

  } catch (error: any) {
    console.error('Try-on error:', error);
    res.status(500).json({ error: error.message || 'Failed to generate try-on' });
  }
});

// API: Paystack Verify
app.post('/api/paystack/verify', async (req, res) => {
  try {
    const { reference, userId, packId } = req.body;

    if (!reference || !userId || !packId) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    // 1. Verify with Paystack
    const paystackResponse = await fetch(`https://api.paystack.co/transaction/verify/${reference}`, {
      headers: {
        Authorization: `Bearer ${process.env.PAYSTACK_SECRET_KEY}`
      }
    });

    const paystackData = await paystackResponse.json();

    if (!paystackData.status || paystackData.data.status !== 'success') {
      return res.status(400).json({ error: 'Payment verification failed' });
    }

    // 2. Identify credits to add
    const pack = {
      starter: 5,
      popular: 15,
      value: 40
    }[packId as string] || 0;

    if (pack === 0) {
      return res.status(400).json({ error: 'Invalid pack ID' });
    }

    // 3. Update user credits
    const { data: profile, error: profileError } = await supabaseAdmin
      .from('profiles')
      .select('credits')
      .eq('id', userId)
      .single();

    if (profileError || !profile) {
      return res.status(404).json({ error: 'Profile not found' });
    }

    await supabaseAdmin
      .from('profiles')
      .update({ credits: profile.credits + pack })
      .eq('id', userId);

    // 4. Record transaction
    await supabaseAdmin.from('credit_transactions').insert({
      user_id: userId,
      amount: pack,
      reference: reference,
      type: 'purchase'
    });

    res.json({ success: true, newBalance: profile.credits + pack });

  } catch (error: any) {
    console.error('Paystack error:', error);
    res.status(500).json({ error: error.message || 'Failed to verify payment' });
  }
});

// Vite middleware setup
async function startServer() {
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
