import type { VercelRequest, VercelResponse } from '@vercel/node';
import { GoogleGenAI } from '@google/genai';
import { createClient } from '@supabase/supabase-js';

const supabaseAdmin = createClient(
  process.env.VITE_SUPABASE_URL || '',
  process.env.SUPABASE_SERVICE_ROLE_KEY || ''
);

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY as string,
});

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { userId, userPhotoUrl, garmentId } = req.body;

    if (!userId || !userPhotoUrl || !garmentId) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    // 1. Check user credits
    const { data: profile, error: profileError } = await supabaseAdmin
      .from('profiles')
      .select('credits')
      .eq('id', userId)
      .single();

    if (profileError || !profile) {
      return res.status(404).json({ error: 'Profile not found' });
    }

    if (profile.credits < 1) {
      return res.status(402).json({ error: 'Insufficient credits' });
    }

    // 2. Get garment details
    const { data: garment, error: garmentError } = await supabaseAdmin
      .from('garments')
      .select('*')
      .eq('id', garmentId)
      .single();

    if (garmentError || !garment) {
      return res.status(404).json({ error: 'Garment not found' });
    }

    // 3. Prepare images for Gemini
    const fetchImageBase64 = async (url: string) => {
      const response = await fetch(url);
      const buffer = await response.arrayBuffer();
      return Buffer.from(buffer).toString('base64');
    };

    const userPhotoBase64 = await fetchImageBase64(userPhotoUrl);
    const garmentPhotoBase64 = await fetchImageBase64(garment.reference_image_url);

    const tryOnPrompt = `
You are performing a virtual clothing try-on. You are given two images:
Image 1 = the person (preserve exactly)
Image 2 = the garment reference (preserve exactly)

Rules, in strict priority order:
1. Preserve the person's face, skin tone, hairstyle, and body proportions from Image 1 with zero alteration. Do not beautify, resize, or change identity.
2. Replace only the clothing area with the garment shown in Image 2. Match its exact fabric pattern, color, embroidery, and silhouette — do not invent a generic version of the garment.
3. Preserve the original pose, camera angle, and background from Image 1.
4. Adjust the garment's drape and folds naturally to fit the person's body and pose — it should look physically worn, not pasted on.
5. Match lighting and shadow direction on the garment to the lighting already present on the person in Image 1.
6. Output a single photorealistic image, no text, no watermark, no side-by-side comparison.

Garment details for reference: ${garment.name}, ${garment.description || ''}, ${garment.fabric_type || ''}, ${garment.color_details || ''}.
    `;

    // 4. Call Gemini
    const result = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: [
        {
          role: 'user',
          parts: [
            { text: tryOnPrompt },
            { inlineData: { mimeType: 'image/jpeg', data: userPhotoBase64 } },
            { inlineData: { mimeType: 'image/jpeg', data: garmentPhotoBase64 } },
          ],
        },
      ],
    });

    let resultBase64 = '';
    for (const part of result.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        resultBase64 = part.inlineData.data;
        break;
      }
    }

    if (!resultBase64) {
      throw new Error('No image generated by Gemini. Ensure the prompt and model support image output.');
    }

    // 5. Upload result to Supabase Storage
    const fileName = `result_${userId}_${Date.now()}.png`;
    const { error: uploadError } = await supabaseAdmin.storage
      .from('tryon-results')
      .upload(fileName, Buffer.from(resultBase64, 'base64'), {
        contentType: 'image/png',
      });

    if (uploadError) {
      throw uploadError;
    }

    const { data: { publicUrl: resultImageUrl } } = supabaseAdmin.storage
      .from('tryon-results')
      .getPublicUrl(fileName);

    // 6. Deduct credit and record history
    await supabaseAdmin.from('profiles').update({ credits: profile.credits - 1 }).eq('id', userId);

    const { data: historyEntry, error: historyError } = await supabaseAdmin
      .from('tryon_history')
      .insert({
        user_id: userId,
        garment_id: garmentId,
        user_photo_url: userPhotoUrl,
        result_image_url: resultImageUrl,
        status: 'completed',
      })
      .select()
      .single();

    if (historyError) {
      console.error('Error saving history:', historyError);
    }

    // 7. Record transaction
    await supabaseAdmin.from('credit_transactions').insert({
      user_id: userId,
      amount: -1,
      type: 'tryon_spend',
    });

    return res.status(200).json({ resultImageUrl, historyId: historyEntry?.id });
  } catch (error: any) {
    console.error('Try-on error:', error);
    return res.status(500).json({ error: error.message || 'Failed to generate try-on' });
  }
}
